-- AlterTable
ALTER TABLE "Bid" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "JobPost" ADD COLUMN     "bidAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "contractorName" TEXT NOT NULL DEFAULT '';
